### ISSUE TITLE
F.document is not a function

### ISSUE THREAD

**Issue by askesis** [uploadcare/uploadcare-widget#563]
After updating the package up to 3.7.8 I had a problem 
I returned to 3.7.7 it works fine

![image](https://user-images.githubusercontent.com/23220242/65758300-8864f980-e121-11e9-9f1d-9571052c377e.png)

**Comment by nd0ut** [comment]
@askesis Thanks for the report! We're fixed this problem and released `v3.7.9`
