### PR TITLE
Semicolon fix 🤦🏻‍♂️

### LINKED ISSUE #563: F.document is not a function
After updating the package up to 3.7.8 I had a problem 
I returned to 3.7.7 it works fine

image

### PR DESCRIPTION
**Pull request by jeetiss**
fix #563

### CODE REVIEW

**Comment by nd0ut** [comment]
https://github.com/uploadcare/uploadcare-widget/issues/563
