### ISSUE TITLE
Widget 3.0.0 error - jQuery.Deferred exception: this.state is not a function

### ISSUE THREAD

**Issue by chvanikoff** [uploadcare/uploadcare-widget#387]
Hi, after upgrade of widget to v3.0.0, I'm getting this error when trying to upload a file. It pops out right after I select a file to upload:

jQuery.Deferred exception: this.state is not a function TypeError: this.state is not a function
    at https://ucarecdn.com/libs/widget/3.0.0/uploadcare.full.min.js:25:7799
    at s (https://ucarecdn.com/libs/widget/3.0.0/uploadcare.full.min.js:9:3554)
    at Object.fireWith [as rejectWith] (https://ucarecdn.com/libs/widget/3.0.0/uploadcare.full.min.js:9:4320)
    at u (https://ucarecdn.com/libs/widget/3.0.0/uploadcare.full.min.js:9:5965)
    at https://ucarecdn.com/libs/widget/3.0.0/uploadcare.full.min.js:9:5986
    at c (https://ucarecdn.com/libs/widget/3.0.0/uploadcare.full.min.js:9:5536)
    at u (https://ucarecdn.com/libs/widget/3.0.0/uploadcare.full.min.js:9:5850) undefined

Here are global constants for the widget:
```html
<script>
    UPLOADCARE_PUBLIC_KEY = '6a8ad67491f39f548826';
    UPLOADCARE_TABS = 'file url gdrive dropbox';
    UPLOADCARE_IMAGES_ONLY = true;
</script>
<script charset="utf-8" src="https://ucarecdn.com/libs/widget/3.0.0/uploadcare.full.min.js"></script>
```
and here is the input:
```jsx
<input ref="image_url"
            type="hidden"
            role="uploadcare-uploader"
            data-image-shrink="1024x768 80%" />
```

**Comment by chvanikoff** [comment]
Jsfiddle demo as per your request: https://jsfiddle.net/q2ma5fbr/

**Comment by chvanikoff** [comment]
Looks like this is where the error is being thrown: https://github.com/uploadcare/uploadcare-widget/blob/5a3fadd8f643e4a708481c84b888cd8aefffe663/app/assets/javascripts/uploadcare/utils/image-processor.coffee#L38

**Comment by Zmoki** [comment]
@chvanikoff hi! Thank you for issue. Yes, with the `image-shrink` setting error occurs in image proccessor.

Fixing the bug will take releasing a patched version. This will most likely occur on Monday, Jul, 3.

**Comment by chvanikoff** [comment]
Thanks for the update, hope to see the patch soon
