### ISSUE TITLE
"a.default.extend is not a function" when migrating from 3.19 -> 3.20

### ISSUE THREAD

**Issue by Kamilczak020** [uploadcare/uploadcare-widget#937]
## Description
After migrating to 3.20, app build process started crashing with the following:
```bash
info  - Collecting page data ..TypeError: a.default.extend is not a function
    at /Users/greenchill/Documents/webdev/brevy/node_modules/uploadcare-widget/uploadcare.lang.en.min.js:10:17490
    at /Users/greenchill/Documents/webdev/brevy/node_modules/uploadcare-widget/uploadcare.lang.en.min.js:10:84
    at Object.<anonymous> (/Users/greenchill/Documents/.../node_modules/uploadcare-widget/uploadcare.lang.en.min.js:10:236)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.25118 (/Users/greenchill/Documents/webdev/.../pages/articles/[articleId].js:9383:51)
```

For now, we've reverted to 3.19 and the issue is gone.

### Expected result

Since this is not a major version release, it should not come with a breaking change (In case something changed in the API we haven't caught).

### Platform
Used in Next.js.
If I have a little bit more time I might try to create a minimal repro and narrow down if the issue maybe is specific to next?
If so, I'll update this PR with my findings.

### Environment
- widget version: 3.20
- `node -v`: 16.17.1
- `yarn -v`: 1.22.19

**Comment by nd0ut** [comment]
Hey @Kamilczak020, 

sorry for breaking your app. It's fixed in [`v3.20.1`](https://github.com/uploadcare/uploadcare-widget/compare/v3.20.0...v3.20.1)
